"""empty message

Revision ID: 08fbbf36aea6
Revises: 
Create Date: 2021-09-04 21:22:59.606289

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '08fbbf36aea6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('mode', postgresql.ENUM('INVITATION', name='mode'), nullable=True),
    sa.Column('secret', postgresql.BYTEA(), nullable=True),
    sa.Column('modified', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('title', sa.VARCHAR(length=30), nullable=True),
    sa.Column('details', sa.VARCHAR(length=500), nullable=True),
    sa.Column('deadline', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_id'), 'project', ['id'], unique=False)
    op.create_index(op.f('ix_project_mode'), 'project', ['mode'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_mode'), table_name='project')
    op.drop_index(op.f('ix_project_id'), table_name='project')
    op.drop_table('project')
    # ### end Alembic commands ###
