"""Add archive column

Revision ID: 1ad69a25ecdc
Revises: 53766b47421d
Create Date: 2021-09-11 11:46:56.256089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ad69a25ecdc'
down_revision = '53766b47421d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('archive', sa.BOOLEAN(), nullable=True, server_default='false'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'archive')
    # ### end Alembic commands ###
