"""Add item table

Revision ID: 53766b47421d
Revises: 08fbbf36aea6
Create Date: 2021-09-07 22:18:22.379207

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '53766b47421d'
down_revision = '08fbbf36aea6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('mode', postgresql.ENUM('WISH', name='item_mode'), nullable=True),
    sa.Column('secret', postgresql.BYTEA(), nullable=True),
    sa.Column('modified', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('title', sa.VARCHAR(length=32), nullable=True),
    sa.Column('link', sa.VARCHAR(length=512), nullable=True),
    sa.Column('cost', sa.INTEGER(), nullable=True),
    sa.Column('relevance', sa.BOOLEAN(), server_default='true', nullable=True),
    sa.Column('project_ids', postgresql.ARRAY(postgresql.UUID()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_id'), 'item', ['id'], unique=False)
    op.create_index(op.f('ix_item_mode'), 'item', ['mode'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_mode'), table_name='item')
    op.drop_index(op.f('ix_item_id'), table_name='item')
    op.drop_table('item')
    # ### end Alembic commands ###
